global proc shelf_vvsMayaTools () {
    global string $gBuffStr;
    global string $gBuffStr0;
    global string $gBuffStr1;

    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 35
        -enable 1
        -width 38
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "Picker Loader" 
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.521569 0.65098 
        -align "center" 
        -label "Picker Loader" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -font "plainLabelFont" 
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.5 
        -image "dreamwallpicker.png" 
        -image1 "dreamwallpicker.png" 
        -style "iconOnly" 
        -marginWidth 0
        -marginHeight 1
        -command "import load_picker;load_picker.create_picker_loader()" 
        -sourceType "python" 
        -commandRepeatable 1
        -flat 1
    ;
    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "BR PlayBlast Tool" 
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.521569 0.65098 
        -align "center" 
        -label "BR PlayBlast Tool" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -font "plainLabelFont" 
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.5 
        -image "action_64.png" 
        -image1 "action_64.png" 
        -style "iconOnly" 
        -marginWidth 0
        -marginHeight 1
        -command "import ani_BR.play_blast.play_blast as pl;pl.PlayBlastWidget.display()" 
        -sourceType "python" 
        -commandRepeatable 1
        -flat 1
    ;

} 
